### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Synaxis**
Hi ! . Do you want to help us withOpenSource Battlefield Heroes Login system and Fesl system ?

### CODE REVIEW

**Comment by piotrkubisa** [comment]
Do you use Telegram instant messenger? It would be great if you could jump into newly-created https://t.me/bfp4flimiter channel. :)

**Comment by Synaxis** [comment]
Hey ! I',m Sorry for the delay , this is my alt email . I cant type nothing
on the telegram
https://discord.gg/nu2RTH
Can you come on discord?

On Aug 14, 2017 7:30 AM, "Piotr Kubisa" <notifications@github.com> wrote:

Do you use Telegram instant messenger? Could you jump into
https://t.me/bfp4flimiter channel?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/piotrkubisa/bfp4f-limiter/pull/15#issuecomment-322156336>,
or mute the thread

**Comment by synaxis** [comment]
Please , because some people are making money with the code and this is why
i started the open source project


2017-08-24 13:38 GMT-07:00 Caio Torquato <01xtor@gmail.com>:

> Hey ! I',m Sorry for the delay , this is my alt email . I cant type
> nothing on the telegram
> https://discord.gg/nu2RTH
> Can you come on discord?
>

**Pull request closed without merging**
